
spring.application.name=ecommerce_backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://project-db.cybs6qwkkj0d.us-east-1.rds.amazonaws.com:3306/vishwajeet_ecomm
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.data.rest.base-path=/api
